### PR TITLE
Adds all of the separate xbox buttons

### PR DESCRIPTION
**Pull request by Sephdude**

### CODE REVIEW

**Comment by smoser** [comment]
@Sephdude thanks for this pull request.

Can you remove the simgui-ds.json, simgui-window.json and simgui.json

Those files are not related to the change.  I've done a pull request to have git ignore them in the future in #8

**Review by smoser — COMMENTED** [review]
@Sephdude , I deleted the 3 simgui files so now you just have the code changes to the misc/robot22sim.yaml.

We'd have liked also to have the generated code changes, not just the robot22sim.yaml.

I'm going to land this, and then we can generate the changes from it later.

Thanks,

**Review by smoser — APPROVED** [review]

**Comment by Sephdude** [comment]
Thanks, sorry my internet wasnt working

**Comment by smoser** [comment]
> Thanks, sorry my internet wasnt working

If you're able, you can generate the code and do a new PR.

Just create a new branch, run the robot builder, generate code, commit, create pr.

**Pull request merged**
